@startuml

autonumber
Actor User
Participant Clock
Participant TasterRIn
Participant TasterR
Participant TasterROut
Participant TasterSIn
Participant TasterS
Participant TasterSOut
Participant FlipFlopInS
Participant FlipFlopInR
Participant FlipFlop
Participant FlipFlopOut
Participant inLED
Participant LED


User -> TasterR: Press()
Clock --> TasterR : T1
TasterR -> TasterR: save()
Clock --> TasterS: T1
FlipFlop --> FlipFlop: calc()
Clock --> FlipFlop: T1
Clock --> LED: T1


TasterSOut -> FlipFlopInS: setInput(S)
TasterROut -> FlipFlopInR: setInput(R)
FlipFlopOut -> inLED: setInput(R&S)
inLED -> LED: setInputState


Clock --> TasterR : T2
Clock --> TasterS: T2
Clock --> FlipFlop: T2
Clock --> LED: T2

@enduml


