@startuml

abstract class Componetes{
 + {abstract} calc()
}

class Taster {
 + Taster()
}

class FlipFlop{
 + FlipFlop()
 + state: int
 + set()
 + reset()
 + q()
 + notQ()
}

class LED1{
 + LED1()
}

class LED2{
 + LED2()
}

class AND{
 + AND()
}

Componetes <|-- FlipFlop
Componetes <|-- AND
Componetes <|-- Taster

@enduml